strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-latest'
    macOS:
      imageName: 'macOS-latest'
    Windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

trigger:
- master

variables: 
    BuildConfiguration: 'Release'

steps:
- task: CredScan@2
  displayName: CredScan
  inputs:
    toolMajorVersion: 'V2'
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- task: PoliCheck@1
  displayName: PoliCheck
  inputs:
    inputType: 'Basic'
    targetType: 'F'
    targetArgument: '$(Build.SourcesDirectory)'
    result: 'PoliCheck.xml'
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:Build /p:Configuration=$(buildConfiguration)'

- task: BinSkim@3
  displayName: BinSkim
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    AnalyzeTarget: 'artifacts\$(buildConfiguration)\*.dll;'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
  displayName: 'Post Analysis'
  inputs:
    BinSkim: true
    CredScan: true
    PoliCheck: true
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- task: CopyFiles@2
  displayName: 'Copy artifacts directory to $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'artifacts\**'
    TargetFolder: '$(build.artifactstagingdirectory)\artifacts'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))